# docker-compose up -d --build
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito_reauth__fastapi_app
    ports:
      - "8000:8000"  # Пробрасываем порт для доступа к FastAPI
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379  # Порт Redis
    volumes:
      - ./cookies:/app/cookies

  redis:
    image: redis:latest
    container_name: avito_reauth__redis
    ports:
      - "6379:6379"  # Пробрасываем порт для Redis (опционально)
    command: ["redis-server", "--appendonly", "yes"]  # Настройки Redis для сохранения данных

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tasks flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
